#ifndef _CONSTANTS_
#define _CONSTANTS_

#define MAXTHREADS 100
#define BROADCAST_PORT 20000
#define MAX_MESSAGE_LEN 100 

enum THREADS
{
    THREAD_CLIENT_INPUT,
    THREAD_CLIENT_SIGNAL_CATCHER,
    THREAD_CLIENT_WAKEUP_CATCHER,
    THREAD_SERVER_MONITORING,
    THREAD_SERVER_SLEEP_SOCKET,
    THREAD_SERVER_INPUT,
    THREAD_SERVER_WAKE_SIGNAL
};

#endif